#ifndef NUMREPLIES_HPP
#define NUMREPLIES_HPP

#define RPL_NAMREPLY "353"
#define ERR_NEEDMOREPARAMS "461"
#define ERR_PASSWDMISMATCH "464"
#define ERR_NOTREGISTERED "451"
#define ERR_NICKNAMEINUSE "433"
#define ERR_NOSUCHCHANNEL "403"
#define ERR_INVITEONLYCHAN "473"
#define ERR_CHANNELISFULL "471"
#define ERR_ERRONEUSNICKNAME "432"
#define ERR_BADCHANNELKEY "475"

#endif //NUMREPLIES_HPP
